version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: nest
    networks:
      - tutorials # In the tutorial he uses "freecodecamp"
networks:
  tutorials: # In the tutorial he uses "freecodecamp"
